// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workflow.Api.Data;

#nullable disable

namespace Workflow.Api.Data.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20261001135444_PersonalTaskListIndexes")]
    partial class PersonalTaskListIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workflow.Api.Models.AccessException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Level")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "DepartmentId");

                    b.HasIndex("OrganizationId", "UserId");

                    b.ToTable("AccessExceptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccessExceptions_Kind", "\"Kind\" IN ('Grant', 'Deny')");

                            t.HasCheckConstraint("CK_AccessExceptions_Level", "(\"Kind\" = 'Grant' AND \"Level\" IN ('View', 'Edit')) OR (\"Kind\" = 'Deny' AND \"Level\" IS NULL)");

                            t.HasCheckConstraint("CK_AccessExceptions_Window", "\"StartsAt\" IS NULL OR \"EndsAt\" IS NULL OR \"StartsAt\" < \"EndsAt\"");
                        });
                });

            modelBuilder.Entity("Workflow.Api.Models.ActingManagerDelegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DelegateUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DelegatorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "DelegateUserId");

                    b.HasIndex("OrganizationId", "DelegatorUserId");

                    b.HasIndex("OrganizationId", "DepartmentId");

                    b.ToTable("ActingManagerDelegations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActingManagerDelegations_Window", "\"StartsAt\" < \"EndsAt\"");
                        });
                });

            modelBuilder.Entity("Workflow.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Workflow.Api.Models.AutomationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<Guid>("AutomationTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RetryOfRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RetryOfRunId");

                    b.HasIndex("AutomationTaskId", "QueuedAt");

                    b.ToTable("AutomationRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_AutomationRuns_Attempt", "\"Attempt\" >= 1");

                            t.HasCheckConstraint("CK_AutomationRuns_Status", "\"Status\" IN ('Queued', 'Running', 'Succeeded', 'Failed', 'Retrying')");
                        });
                });

            modelBuilder.Entity("Workflow.Api.Models.AutomationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "DepartmentId");

                    b.HasIndex("OrganizationId", "OwnerUserId");

                    b.ToTable("AutomationTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_AutomationTasks_Status", "\"Status\" IN ('Active', 'Paused')");
                        });
                });

            modelBuilder.Entity("Workflow.Api.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Path"), new[] { "text_pattern_ops" });

                    b.HasIndex("OrganizationId", "ManagerUserId");

                    b.HasIndex("OrganizationId", "ParentId", "Name")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OrganizationId", "ParentId", "Name"), false);

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Departments_Depth", "\"Depth\" >= 0");

                            t.HasCheckConstraint("CK_Departments_NotOwnParent", "\"ParentId\" IS NULL OR \"ParentId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("Workflow.Api.Models.DepartmentMembership", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("DepartmentId", "UserId");

                    b.HasIndex("OrganizationId", "DepartmentId");

                    b.HasIndex("OrganizationId", "UserId");

                    b.ToTable("DepartmentMemberships", (string)null);
                });

            modelBuilder.Entity("Workflow.Api.Models.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrimaryDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "PrimaryDepartmentId");

                    b.ToTable("Memberships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Memberships_Role", "\"Role\" IN ('Member', 'Manager', 'Admin')");
                        });
                });

            modelBuilder.Entity("Workflow.Api.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Workflow.Api.Models.PersonalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "AssigneeUserId");

                    b.HasIndex("OrganizationId", "DepartmentId");

                    b.HasIndex("OrganizationId", "OwnerUserId");

                    b.HasIndex(new[] { "OrganizationId", "CreatedAt", "Id" }, "IX_PersonalTasks_Org_CreatedAt_Id")
                        .IsDescending(false, true, true);

                    b.HasIndex(new[] { "OrganizationId", "Status", "CreatedAt", "Id" }, "IX_PersonalTasks_Org_Status_CreatedAt_Id")
                        .IsDescending(false, false, true, true);

                    b.ToTable("PersonalTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_PersonalTasks_Status", "\"Status\" IN ('ToDo', 'InProgress', 'Done', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Workflow.Api.Models.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("Workflow.Api.Models.AccessException", b =>
                {
                    b.HasOne("Workflow.Api.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workflow.Api.Models.ActingManagerDelegation", b =>
                {
                    b.HasOne("Workflow.Api.Models.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DelegateUserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DelegatorUserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ActingManagerDelegations_Memberships_OrganizationId_Delega~1");

                    b.HasOne("Workflow.Api.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workflow.Api.Models.AutomationRun", b =>
                {
                    b.HasOne("Workflow.Api.Models.AutomationTask", null)
                        .WithMany("Runs")
                        .HasForeignKey("AutomationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.AutomationRun", null)
                        .WithMany()
                        .HasForeignKey("RetryOfRunId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Workflow.Api.Models.AutomationTask", b =>
                {
                    b.HasOne("Workflow.Api.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OwnerUserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Workflow.Api.Models.Department", b =>
                {
                    b.HasOne("Workflow.Api.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ManagerUserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Departments_Memberships_Manager");

                    b.HasOne("Workflow.Api.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ParentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Workflow.Api.Models.DepartmentMembership", b =>
                {
                    b.HasOne("Workflow.Api.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workflow.Api.Models.Membership", b =>
                {
                    b.HasOne("Workflow.Api.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PrimaryDepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Workflow.Api.Models.PersonalTask", b =>
                {
                    b.HasOne("Workflow.Api.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AssigneeUserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Workflow.Api.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workflow.Api.Models.Membership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OwnerUserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Workflow.Api.Models.AutomationTask", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
